export interface ScrambleWord {
  word: string;
  hint: string;
}

export const WORDS: ScrambleWord[] = [
  { word: 'PLANET', hint: 'Space' },
  { word: 'GALAXY', hint: 'Space' },
  { word: 'ROCKET', hint: 'Space' },
  { word: 'COMET', hint: 'Space' },
  { word: 'CRICKET', hint: 'Sport' },
  { word: 'FOOTBALL', hint: 'Sport' },
  { word: 'STADIUM', hint: 'Sport' },
  { word: 'TROPHY', hint: 'Sport' },
  { word: 'MANGO', hint: 'Food' },
  { word: 'BIRYANI', hint: 'Food' },
  { word: 'PANEER', hint: 'Food' },
  { word: 'SAMOSA', hint: 'Food' },
  { word: 'NOODLES', hint: 'Food' },
  { word: 'ELEPHANT', hint: 'Animal' },
  { word: 'PENGUIN', hint: 'Animal' },
  { word: 'DOLPHIN', hint: 'Animal' },
  { word: 'GIRAFFE', hint: 'Animal' },
  { word: 'PEACOCK', hint: 'Animal' },
  { word: 'LAPTOP', hint: 'Technology' },
  { word: 'BROWSER', hint: 'Technology' },
  { word: 'KEYBOARD', hint: 'Technology' },
  { word: 'PASSWORD', hint: 'Technology' },
  { word: 'CHARGER', hint: 'Technology' },
  { word: 'GUITAR', hint: 'Music' },
  { word: 'MELODY', hint: 'Music' },
  { word: 'CONCERT', hint: 'Music' },
  { word: 'ISLAND', hint: 'Geography' },
  { word: 'DESERT', hint: 'Geography' },
  { word: 'VOLCANO', hint: 'Geography' },
  { word: 'GLACIER', hint: 'Geography' },
  { word: 'HARBOUR', hint: 'Geography' },
  { word: 'DIRECTOR', hint: 'Movies' },
  { word: 'VILLAIN', hint: 'Movies' },
  { word: 'TRAILER', hint: 'Movies' },
  { word: 'SEQUEL', hint: 'Movies' },
  { word: 'UMBRELLA', hint: 'Everyday thing' },
  { word: 'MIRROR', hint: 'Everyday thing' },
  { word: 'PILLOW', hint: 'Everyday thing' },
  { word: 'WALLET', hint: 'Everyday thing' },
  { word: 'BALCONY', hint: 'Everyday thing' },
];
